"""Add ML fields

Revision ID: 503bade18a30
Revises: 57a9fa006ab3
Create Date: 2026-01-27 20:12:16.608451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503bade18a30'
down_revision: Union[str, None] = '57a9fa006ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('heatmap_path', sa.String(), nullable=True))
    op.add_column('results', sa.Column('model_version', sa.String(), nullable=True))
    op.alter_column('results', 'is_anomaly',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='is_anomaly::boolean')
    op.drop_column('results', 'detection_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('detection_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('results', 'is_anomaly',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('results', 'model_version')
    op.drop_column('results', 'heatmap_path')
    op.drop_column('results', 'threshold')
    op.drop_column('results', 'anomaly_score')
    # ### end Alembic commands ###
