"""add fields to history

Revision ID: 85e92479c5e9
Revises: 02590557034a
Create Date: 2026-02-21 23:35:42.900560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e92479c5e9'
down_revision: Union[str, None] = '02590557034a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('heatmap_path', sa.String(), nullable=True))
    op.add_column('history', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'model_version')
    op.drop_column('history', 'threshold')
    op.drop_column('history', 'heatmap_path')
    # ### end Alembic commands ###
